### ISSUE TITLE
A mistake I met when I run "python test.py --config config/demo-test.yml"

### ISSUE THREAD

**Issue by TristanWH** [jiangjiechen/HedModTmplGen#3]
Hello! It's an honor to use and replicate your code. Here I have a small question that I hope you can answer. When I run the following code:
'''
python test.py --config config/demo-test.yml
'''
The following error appears:
'''
[2022-11-07 03:02:27 WARNING] demo test config file of data10K
[2022-11-07 03:02:27 INFO] exp/DEMO/demo-1_step_5000.pt/test_pred.log
/home/tristan/anaconda3/envs/py365/lib/python3.6/site-packages/torch/nn/modules/rnn.py:61: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
[2022-11-07 03:02:30 INFO] Building test data...
Traceback (most recent call last):
  File "test.py", line 92, in <module>
    translate_them_all(opt)
  File "test.py", line 81, in translate_them_all
    main(opt)
  File "test.py", line 47, in main
    for i, (src_shard, tmpl_shard, src2_shard, tgt_shard) in enumerate(shard_pairs):
  File "/home/tristan/HedModTmplGen-master/monmt/utils/misc.py", line 78, in split_corpus
    with open(data, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/DEMO/demo-1_step_5000.pt/src2-test.txt'
'''
And I can't find why the error is reported, and there is no exception in the training log.
So would you mind to tell me what lead to this result?

**Comment by jiangjiechen** [comment]
Hi Tristan, thank you for your interest in this work and the efforts for updating this code!

If I remember correctly, `src2-test.txt` is the template file you generate during pass 1. So a simple copy command will do. A piece of evidence is that, according to the data files in Google Drive, `tmpl-valid.txt` == `src2-valid.txt`.

**Comment by TristanWH** [comment]
Thank you for your reply and patience, and I hope you will forgive me for my foolishness.I didn't find any ways to run copy-command things.And I can only get :
'''
*** Infobox loaded in 0h 0m 0.27s. ***
*** All together 45603/45603 words, 498 properties. ***
*** Infobox loaded in 0h 0m 0.04s. ***
*** All together 45603/45603 words, 498 properties. ***
*** Infobox loaded in 0h 0m 0.04s. ***
*** All together 45603/45603 words, 498 properties. ***
'''
when I run 
'''
python build_dataset.py --config condig/demo-prep.yml
'''
So can you please answer this question in more detail? I will be grateful!!!
